### ISSUE TITLE
Problem beim Speichern von Formularen in FormdataBackend.php

### ISSUE THREAD

**Issue by havutcuoglu** [obendev/efg#4]
Danke für dein EFG Fix und das du es hier zur Verfügung stellst.

Was ich aber festgestellt habe, wenn man im Backend die Formulare öffnet und nach bearbeiten der Einstellungen sie speichern möchte, wird ein Fehler durch system/modules/classes/FormdataBackend.php verursacht (z.B. Formulardaten Speichern aktiviert).

Das Problem liegt daran, das die Klasse Automator die generateConfigCache, generateDcaCache und generateDcaExtracts Methoden nicht mehr beinhaltet.

Das Problem kann man beheben, in dem man die Zielen 410 bis 418 entfernt oder kommentiert.

```
// Rebuild internal cache
if (!$GLOBALS['TL_CONFIG']['bypassCache'])
{
	$this->import('Automator');
        
	$this->Automator->generateConfigCache();
	$this->Automator->generateDcaCache();
	$this->Automator->generateDcaExtracts();
}
```

Vielleicht kannst du es in deine Repository aktualisieren.

**Comment by obendev** [comment]
Hey, thank you very much for the bug report. Could you do a pull request on this one?
I will review it on Monday. :)
